### ISSUE TITLE
Please fix CI setup

### ISSUE THREAD

**Issue by hillu** [spyre-project/spyre#12]
I believe that the CI setup was broken due to invalidated credentials that I had granted towards CircleCI when my account was removed from the @DCSO organization ([cf.](https://travis-ci.org/DCSO/spyre/builds/598523424)). Please fix so tagged builds are released with a binary build. :-)

**Comment by rhaist** [comment]
Maybe we can move the cross platform builds to the new Github Actions:

https://github.com/features/actions

**Comment by hillu** [comment]
Fixed as of 2ac6759c4a90be34a2d6b1bfc1bd48805a1c128b
