### ISSUE TITLE
Use Go modules

### ISSUE THREAD

**Issue by hillu** [spyre-project/spyre#15]
For better or worse, go dep fallen out of [fashion](http://n-gate.com/hackernews/2018/07/), so we might as well get with the program.

(Of course this will not rid us of building the 3rd-party libraries.)

**Comment by rhaist** [comment]
I just pushed necessary files for go modules.
I did not want to delete the `Gopkg.lock` and `Gopkg.toml` before checking back with you that this is no longer needed :)

**Comment by hillu** [comment]
Thanks. Next step: Makefile munging.
