### ISSUE TITLE
Re-think handling of command line parameters, configuration file

### ISSUE THREAD

**Issue by hillu** [spyre-project/spyre#16]
There are a few problems regarding runtime configuration, e.g.:
1. configuration via the command line (and/or a `params.txt` file is clumsy as it is and will become worse as we add modules.
2. Thus far, spyre looks opportunistically for YARA files, either in the directory that holds the executable, or in an embedded executable. This is more complicated then necessary and error-prone for fragments of not-so-well-written YARA rule sets. The ad-hoc solution that was added for the `registry` and `eventobj` modules has similar problems.

I am currently leaning toward using a YAML-based configuration and mapping command line parameters directly to YAML document paths.

Every module could then have its default "seed" file(s) and a section in the configuration file where those files can be overridden.

**Comment by rhaist** [comment]
We are using cobra/viper for file, network and cli argument support in most applications. This could be a good solution here as well.

**Comment by hillu** [comment]
While I believe that viper could be coerced to do what I have in mind, I seem to remember that it's a bit excessive on the dependencies side.
```
$ git clone https://github.com/spf13/viper
[…]
$ cd viper && go mod  graph | awk '{print $2}' | sort -u | wc -l
274
```
For whatever this metric is worth (different versions due the stupid minimum version selection mechanism implemented in Go Modules), we are currently at 21. :-)

I'd definitely prefer something more … lightweight.

**Comment by rhaist** [comment]
FTR: by using your recently discovered method:

`go mod download -json | jq -r '[.Path,"=",.Version]|add' | wc -l` 

we end up with `155` dependencies.
