### ISSUE TITLE
Make the build chain work on OSX

### ISSUE THREAD

**Issue by rhaist** [spyre-project/spyre#28]
After installing gnu-make and openssl via homebrew the make build currently fails.

**Comment by hillu** [comment]
You should not need to install openssl via homebrew because as a build-dependency of YARA, it is supposed to be built using the rules in `3rdparty.mk`.

**Comment by hillu** [comment]
Sadly, I don't have access to a MacOSX build environment (and I don't want to do the edit-compile-rinse-repeat dance through a CI service). I am currently working on getting Spyre to build on FreeBSD. This is all about the 3rdparty libraries and most of this stuff can probably be transferred to MacOSX.

**Comment by n3x77** [comment]
Hi after first testing there are some issues with static builds on MacOS:

`[+] Building spyre...
[+] GOROOT=/usr/local/opt/go/libexec GOOS=darwin GOARCH=amd64 CC=cc
[+] PKG_CONFIG_PATH=/Users/n3x77/git/spyre/_3rdparty/tgt/x86_64-apple-darwin19.6.0/lib/pkgconfig
mkdir -p _build/x86_64-apple-darwin19.6.0
/usr/local/opt/go/libexec/bin/go build \
        -ldflags '-w -s -linkmode=external -extldflags "-static"' \
        -tags yara_static \
        -o _build/x86_64-apple-darwin19.6.0/spyre github.com/spyre-project/spyre/cmd/spyre
go: github.com/hillu/go-archive-zip-crypto@v0.0.0-20200712202847-bd5cf365dd44: Get "https://proxy.golang.org/github.com/hillu/go-archive-zip-crypto/@v/v0.0.0-20200712202847-bd5cf365dd44.mod": dial tcp 216.58.208.49:443: i/o timeout
gmake: *** [Makefile:100: _build/x86_64-apple-darwin19.6.0/spyre] Error 1

 ~/git/spyre  master !1 ?1  gmake                                                                                                                                                          2 ✘  8m 19s
sed: 1: "/var version/{ s/.*"\(. ...": extra characters at the end of p command
[+] Building spyre...
[+] GOROOT=/usr/local/opt/go/libexec GOOS=darwin GOARCH=amd64 CC=cc
[+] PKG_CONFIG_PATH=/Users/n3x77/git/spyre/_3rdparty/tgt/x86_64-apple-darwin19.6.0/lib/pkgconfig
mkdir -p _build/x86_64-apple-darwin19.6.0
/usr/local/opt/go/libexec/bin/go build \
        -ldflags '-w -s -linkmode=external -extldflags "-static"' \
        -tags yara_static \
        -o _build/x86_64-apple-darwin19.6.0/spyre github.com/spyre-project/spyre/cmd/spyre
go: downloading github.com/mitchellh/go-ps v1.0.0
go: downloading github.com/spf13/afero v1.3.2
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/hillu/go-archive-zip-crypto v0.0.0-20200712202847-bd5cf365dd44
go: downloading github.com/hillu/go-yara/v4 v4.0.2
go: downloading golang.org/x/text v0.3.0
go: downloading golang.org/x/crypto v0.0.0-20190820162420-60c769a6c586
# github.com/spyre-project/spyre/cmd/spyre
/usr/local/opt/go/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

gmake: *** [Makefile:100: _build/x86_64-apple-darwin19.6.0/spyre] Error 2`

This maybe related to this post, of course we want to have a static build of spyre:

https://stackoverflow.com/questions/3801011/ld-library-not-found-for-lcrt0-o-on-osx-10-6-with-gcc-clang-static-flag.

I'm currently investigating if this works: https://dropline.net/2015/10/static-linking-on-mac-os-x/

**Comment by hillu** [comment]
Fixed via 797d6ed227088710c875d193c9e8db3b9ac96683; Thanks to @n3x77 for testing.
