### ISSUE TITLE
Extend spyre to build on Fedora

### ISSUE THREAD

**Issue by 0mbi** [spyre-project/spyre#40]
spyre does not build on Fedora because make fails with
```
3rdparty.mk:14: *** (Currently) unsupported native triplet x86_64-redhat-linux.  Stop.
```

**Comment by 0mbi** [comment]
Add  an or to check for _-linux_ should fix it.

**Comment by hillu** [comment]
Have a look at [3rdparty.mk:19ff](https://github.com/spyre-project/spyre/blob/8963cac8bcb82ff2227efefc278ef0c479c81584/3rdparty.mk#L19), you should be able to extend the condition in the `$(if  …)` above accordingly. If it builds on your machine, do a PR and we'll see if you broke anything. :-)

**Comment by 0mbi** [comment]
This fixes it:
https://github.com/0mbi/spyre/commit/2a1c02c700146eb9d10aba2847566f3ddf0dfb95

However, I fail to get to build yara.4.02...wip
