### ISSUE TITLE
Option to exclude vmtoolsd.exe Process from procscan

### ISSUE THREAD

**Issue by anna-g-arbeiter** [spyre-project/spyre#44]
If you copy&paste procscan.yar and filescan.yar into a VMWare VM, then all procscan rules will match on vmtoolsd.exe process.

**Comment by hillu** [comment]
Good idea. Of course, we wouldn't want to hard-code process exclude lists into Spyre, but rather offer a user option to specify such lists.

**Comment by hillu** [comment]
Closed via bb546fae685d7212b65314cb2cb2de130fe881a1, `--proc-ignore` switch
