### ISSUE TITLE
How to build for 32-bit program of linux on 64-bit linux using musl-gcc

### ISSUE THREAD

**Issue by N0body007** [spyre-project/spyre#76]
Hi, I don't know how to build for 32-bit program of linux on 64-bit linux using musl-gcc, just like the spyre of i386-linux-musl, which I don't know how to generate on 64-bit linux. I have searched a lot,but don't find the solution.Could you help me out? Thanks in advance.

**Comment by hillu** [comment]
@N0body007 Does my answer help?

**Comment by N0body007** [comment]
I’am sorry for taking so long to reply to you. I've been busy with other things recently and didn't pay attention to GitHub messages. I'am sorry again.
  I have read the makefile you wrote.But I want to build 32-bit program of linux on 64-bit linux using Linux terminal command. I have build 64-bit program of linux successfully using musl-gcc. But when I used the following command to build 32-bit program of linux on 64-bit linux,
"GOOS=linux GOARCH=386 CGO_ENABLED=1 \
  CC=musl-gcc \
  PKG_CONFIG_PATH=${PREFIX_LINUX_MUSL}/lib/pkgconfig \
      go build -ldflags '-extldflags "-static"' -tags yara_static -o simple-yara-musl ./_examples/simple-yara"
I got the one of errors like this "/usr/bin/ld: i386 architecture of input file `/tmp/go-build2117339483/b062/_x008.o' is incompatible with i386:x86-64 output". I don't know how to specify the lib of 32-bit musl gcc.Could you help me out?Thanks again.

**Comment by N0body007** [comment]
Thank you very much for your answer. Through your answer, I know how to solve this problem.

**Comment by hillu** [comment]
Glad I could help. Closing the issue now.
